parameters:
#    saffire_home.example.class: Saffire\HomeBundle\Example

services:
#    saffire_home.example:
#        class: %saffire_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
