parameters:
#    saffire_user.example.class: Saffire\UserBundle\Example

services:
#    saffire_user.example:
#        class: %saffire_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
